### ISSUE TITLE
Could not find es.malvarez.microservices.workshop:api:1.0.1

### ISSUE THREAD

**Issue by McPringle** [manuel-alvarez-alvarez/microservices-workshop#1]
I cloned your repository for the workshop and switched to the branch `monolith_start`. Then I thought it would be a good idea to cache the dependencies beforehand to avoid long download times at the workshop location, so I did a `./gradlew assemble` which failed retrieving two dependencies:

```
$ ./gradlew assemble
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find es.malvarez.microservices.workshop:api:1.0.1.
  Required by:
      project :
> Could not find es.malvarez.microservices.workshop:web:1.0.1.
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.523 secs
```

Well, these look like project internal dependencies and of course they are not on maven central.

**Comment by manuel-alvarez-alvarez** [comment]
Yep, I'm doing a couple of last minute modifications and since I'm using bintray for the dependencies I can't  publish snapshots, it will be ready in a couple of hours and I'll close the issue. Thanks for the feedback.

**Comment by manuel-alvarez-alvarez** [comment]
I've published the binaries to bintray so you should be able to successfuly assemble the project.

Thanks again for your feedback.
